# Generated by Django 3.1.1 on 2020-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='beta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.CharField(default='ss', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='data', max_length=255),
            preserve_default=False,
        ),
    ]
